# Generated by Django 3.2.6 on 2021-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('products', models.CharField(max_length=200)),
                ('order_sales', models.CharField(max_length=200)),
                ('order_units', models.IntegerField(default=0)),
            ],
        ),
    ]
