# Generated by Django 3.2.6 on 2021-08-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderdetails',
            name='order_sales',
            field=models.IntegerField(default=0),
        ),
    ]
